name: Build EXE (Windows) - debug-friendly

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Show python & pip info
        run: |
          python -V
          python -m pip --version
          python -m pip list

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install runtime deps + PyInstaller (including hooks)
        run: |
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller pyinstaller-hooks-contrib pywin32

      - name: PyInstaller build (with log file)
        shell: pwsh
        run: |
          Write-Host "Start PyInstaller..."
          pyinstaller --onefile --noconsole --clean --log-level=DEBUG --name RiepilogoGaranzie app.py 2>&1 | Tee-Object -FilePath pyinstaller.log
          Write-Host "PyInstaller finished. Log saved to pyinstaller.log"

      - name: List dist and build folders
        run: |
          dir
          if (Test-Path build) { Write-Host '--- build folder listing ---'; dir build }
          if (Test-Path dist) { Write-Host '--- dist folder listing ---'; dir dist }

      - name: Upload build artifacts (exe + log)
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            pyinstaller.log
            dist/RiepilogoGaranzie.exe
          retention-days: 30

      - name: Verification - create sample input
        shell: pwsh
        run: |
          @"
1001111 020250724 1 340
1002722 020250724 1 17
"@ > sample_input.txt
          Write-Host "Sample input created."

      - name: Run the built exe on sample (verify)
        shell: pwsh
        run: |
          if (Test-Path dist/RiepilogoGaranzie.exe) {
            Write-Host "Executing exe with sample_input.txt..."
            & .\dist\RiepilogoGaranzie.exe (Resolve-Path sample_input.txt).Path
            Write-Host "Execution finished. Searching for output PDF..."
            Get-ChildItem -Path . -Recurse -Filter "*Riepilogo_Garanzie.pdf" -ErrorAction SilentlyContinue | Select-Object FullName -First 10
          } else {
            Write-Host "EXE not found; skipping verification run."
            exit 0
          }

      - name: Upload verification PDF (if any)
        uses: actions/upload-artifact@v4
        with:
          name: verification-pdf
          path: |
            sample_input_Riepilogo_Garanzie.pdf
          if-no-files-found: ignore
          retention-days: 7
